### ISSUE TITLE
Совместимость GyverOS и EncButton

### ISSUE THREAD

**Issue by waw555** [GyverLibs/GyverOS#2]
Здравствуйте!

При использовании GyverOS и EncButton, кнопка энкодера отрабатывает через раз, а повороты ручки вообще не проходят.

Если в loop отключить OS.tick();, то кнопки и повороты энкодера отрабатывают идеально.

void loop() {
  
  OS.tick();
  enc.tick();

}

В видео "Уроки Ардуино. Как написать скетч: многозадачность на millis() и переключение режимов", GyverOS и EncButton  вместе работают отлично.

В чем может быть причина?

Ниже код, который я пытаюсь немного переделать для себя, и столкнулся с данной проблемой.

Заранее благодарю за помощь!

Код:
`#include <LiquidCrystal_I2C.h>
#include <EEPROM.h>
#include <OneWire.h> 
#include <DallasTemperature.h>
#include <GyverOS.h>
#include <EncButton.h>

GyverOS<5> OS;  // В скобках указывается максимальное количество задач, начиная с 1

//Энкодер
//#define ENCODER_CLK 2 // CLK энкодера
//#define ENCODER_DT 3 // DT энкодера
//#define ENCODER_BTN 4 // Кнопка энкодера
EncButton<EB_TICK, 3, 2, 4> enc(INPUT);  // энкодер с кнопкой <A, B, KEY>, отключаем внутреннюю подтяжку если есть внешняя
// Опциональные дефайн-настройки (показаны по умолчанию)
//#define EB_FAST 30     // таймаут быстрого поворота, мс
//#define EB_DEB 50      // дебаунс кнопки, мс
//#define EB_HOLD 1000   // таймаут удержания кнопки, мс
//#define EB_STEP 500    // период срабатывания степ, мс
//#define EB_CLICK 400   // таймаут накликивания, мс
//Светодиоды
#define LED_GREEN 9 //Зеленый светодиод
#define LED_BLUE 8 //Синий светодиод
//Реле
#define RELAY 5 //Реле
//Датчик температуры
#define SENSOR 7 // Датчик температуры

// Создаем объект OneWire
OneWire oneWire(SENSOR);
// Создаем объект DallasTemperature для работы с сенсорами, передавая ему ссылку на объект для работы с 1-Wire.
DallasTemperature dallasSensors(&oneWire);
// Специальный объект для хранения адреса устройства
DeviceAddress sensorAddress;

//Параметры дисплея
LiquidCrystal_I2C lcd(0x27,16,2);

//Русские буквы
byte Letter_P[8]   = {B11111,B10001,B10001,B10001,B10001,B10001,B10001,B00000,}; // Буква "П"
byte Letter_Y[8]   = {B10001,B10001,B10001,B01010,B00100,B01000,B10000,B00000,}; // Буква "У"
byte Letter_I[8]   = {B10001,B10011,B10011,B10101,B11001,B11001,B10001,B00000,}; // Буква "И"

// Переменные температуры
const int FixMaxTemp= 20; // Максимальная температура, которую можно установить
const int FixMinTemp= -20; // Минимальная температура, которую можно установить
int MaxTemp; // Максимальная температура, при которой происходит отключение реле 
int MinTemp; // пороговая температура
float CurrTemp=0; // Текущая температура
const float Hysteresis=0.2; // Гистерезис

// переменные для хранения состояний пинов 
// (чтобы не производить ненужных считываний)
boolean Encoder_CLK;
boolean Encoder_DT;

// переменные для хранения информации о предыдущих состояниях
// и движениях энкодера
boolean prev11; // предыдущее состояние было 11
boolean clockwise1=true; // переход по часовой стрелке 1 (от 11)
boolean clockwise2=false; // переход по часовой стрелке 2 (от 00)

// переменные для обработки состояния кнопки
int ButtonCount=0;

// переменные, задействованные во время регулировки температуры
int blinkInterval=250; // интервал мигания во время редактирования
boolean blinkState=false; // текущий этап мигания
boolean EditMinTemp=false; //Редактирование минимальной тепературы
boolean EditMaxTemp=false; //Редактирование максимальной температуры
long int lastBlink=0; // время последнего перехода на следующий этап

// обновление значения в EEPROM, если оно отличается
void EEPROM_update(int addr, byte value){
  byte lastValue = EEPROM.read(addr);
  if (lastValue!=value){
    EEPROM.write(addr, value);
  }
}

// обновление информации на дисплее
void lcdUpdate(){
  lcd.createChar(1, Letter_P);
  lcd.createChar(2, Letter_Y);
  lcd.createChar(3, Letter_I);
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("TEM\1EPAT\2PA:");
  lcd.print(CurrTemp); // отображение текущей температуры
  lcd.setCursor(0,1);
  lcd.print("M\3H:");
  if ((blinkState)||(!EditMinTemp)){ // отображение целевой температуры с учётом мигания
    lcd.setCursor(4,1);
    lcd.print(MinTemp);
  }  
  //lcd.print(MinTemp);
  lcd.setCursor(8,1);
  lcd.print("MAKC:");
  if ((blinkState)||(!EditMaxTemp)){ // отображение целевой температуры с учётом мигания
    lcd.setCursor(14,1);
    lcd.print(MaxTemp);
  }
}

//Включить дисплей
void LcdDisplayOn(){
  lcd.setBacklight(true); // Включение подсветки
  lcd.display(); //Включение дисплея
  OS.attach(1, LcdDisplayOff, 20000); //Выключить дисплей через 20 секунд
}

//Выключить дисплей
void LcdDisplayOff(){
  lcd.setBacklight(false); // Отключение подсветки
  lcd.noDisplay(); //Отключение дисплея
}

//Включение выключение реле с учетом гистерезиса
void RelayOnOff(){
  if (CurrTemp){
    if (CurrTemp>=((float)MaxTemp+Hysteresis)){
      digitalWrite(RELAY, LOW);
      digitalWrite(LED_GREEN, HIGH);
      digitalWrite(LED_BLUE, LOW);
    }
    else if (CurrTemp<=((float)MinTemp-Hysteresis)){
      digitalWrite(RELAY, HIGH);
      digitalWrite(LED_BLUE, HIGH);
      digitalWrite(LED_GREEN, LOW);
    }
    if (!EditMinTemp || !EditMaxTemp) lcdUpdate();
  }
}

void BlinkCurrPos(){
    if (EditMinTemp || EditMaxTemp){
      lcdUpdate();
      blinkState = !blinkState;
    }
}

void setup() {
  Serial.begin(9600);
  lcd.begin(16, 2); //Инициализация дисплея - количество символов и строк
  LcdDisplayOn();  //Включить дисплей
  //Задачи
  OS.attach(0, GetCurrTemp, 50); //Получение температуры с датчика каждые 50 ms
  OS.attach(2, RelayOnOff, 1000); //Сравнение температуры каждую секунду
  OS.attach(3, BlinkCurrPos, 250); //Мигаем выбранной позицией каждые 250 ms
  OS.attach(4, lcdUpdate, 100); //Обновляем данные на дисплее каждые 100 ms

  pinMode(LED_GREEN, OUTPUT); //Пин зеленого светодиода
  pinMode(LED_BLUE, OUTPUT); //Пин синего светодиода
  
  pinMode(RELAY, OUTPUT); //Пин реле
  digitalWrite(RELAY, LOW); //Отключаем реле при включении
                                               
  // целевая температура загружается из EEPROM, если она в заданных рамках
  MinTemp = EEPROM.read(0);
  MaxTemp = EEPROM.read(1);
  if ((MinTemp>FixMaxTemp)||(MinTemp<FixMinTemp)){
    MinTemp=2;
    EEPROM.write(0, MinTemp); // Обновляем значения 
  }
  if ((MaxTemp>FixMaxTemp)||(MaxTemp<FixMinTemp)){
    MaxTemp=5;
    EEPROM.write(1, MaxTemp); // Обновляем значения 
  }
  lcdUpdate();
}

//Получение текущей температуры
void GetCurrTemp(){
  static float average = 0; //Средняя температура
  static byte counter = 0; //Счетчик
  dallasSensors.requestTemperatures();
  if (++counter >= 10) {
    counter = 0;
    CurrTemp = average / 10.0;
    average = 0;
  }
  average +=  dallasSensors.getTempCByIndex(0);
}

void loop() {
  
  OS.tick();
  enc.tick();

    if (enc.held()) {
    
    ButtonCount++;
    LcdDisplayOn();

    if (ButtonCount==1){ 
      blinkState=true;
      EditMinTemp=true;
      EditMaxTemp=false;
      EEPROM_update(0, MinTemp);
    
    } else if (ButtonCount==2) {
      blinkState=true;
      EditMaxTemp=true;
      EditMinTemp=false;
      EEPROM_update(1, MaxTemp);
    } else {
      blinkState=false;
      EditMaxTemp=false;
      EditMinTemp=false;
      ButtonCount=0;
    }
    lcdUpdate();
    //encBtnPrevMillis=millisCur;
    Serial.println("Удержание");
  }
  if (enc.click()) {
    LcdDisplayOn();
      blinkState=false;
      EditMaxTemp=false;
      EditMinTemp=false;
      ButtonCount=0;
    Serial.println("Включить дисплей"); 
  }

  if (enc.turn()) {
    Serial.println("turn");

    // можно опросить ещё:
    //Serial.println(enc.counter);  // вывести счётчик
    //Serial.println(enc.fast());   // проверить быстрый поворот
    Serial.println(enc.getDir()); // направление поворота
  }
  // считывание состояния выходов энкодера
  //Encoder_CLK = digitalRead(ENCODER_CLK);
  //Encoder_DT = digitalRead(ENCODER_DT);

  //long int millisCur = millis(); // получаем текущее время с момента запуска
 
  // если в состояние 11 пришли не из 11
  // и 2 раза детектировалось движение 
  // в одну и ту же сторону, то соответствующим 
  // образом изменяем значение переменной 
  /*if (EditMinTemp){
    if ((Encoder_CLK)&&(Encoder_DT)&&(!prev11)){
      //LcdDisplayOn();
      if ((clockwise1)&&(clockwise2)){
        if (MinTemp<FixMaxTemp){
          MinTemp++;
        }
      }
      if ((!clockwise1)&&(!clockwise2)){
        if (MinTemp>FixMinTemp){
          MinTemp--;
        }   
      }        
      //blinkState = true;
      lcdUpdate();  
      prev11 = true;
    }
    // детектирование направления первого перехода (от 11)
    else if ((!Encoder_CLK)&&(Encoder_DT)&&(prev11)){
      clockwise1 = true;
      prev11 = false;
    }
    else if ((Encoder_CLK)&&(!Encoder_DT)&&(prev11)){
      clockwise1 = false;
      prev11 = false;    
    }
    // детектирование направления второго перехода (от 00)
    else if ((!Encoder_CLK)&&(Encoder_DT)&&(!prev11)){
      clockwise2 = false;
    }
    else if ((Encoder_CLK)&&(!Encoder_DT)&&(!prev11)){
      clockwise2 = true;   
    }
  }

  if (EditMaxTemp){
    if ((Encoder_CLK)&&(Encoder_DT)&&(!prev11)){
      //LcdDisplayOn();
      if ((clockwise1)&&(clockwise2)){
        if (MaxTemp<FixMaxTemp){
          MaxTemp++;
        }
      }
      if ((!clockwise1)&&(!clockwise2)){
        if (MaxTemp>FixMinTemp){
          MaxTemp--;
        }   
      }        
      //blinkState = true;
      lcdUpdate();  
      prev11 = true;
    }
    // детектирование направления первого перехода (от 11)
    else if ((!Encoder_CLK)&&(Encoder_DT)&&(prev11)){
      clockwise1 = true;
      prev11 = false;
    }
    else if ((Encoder_CLK)&&(!Encoder_DT)&&(prev11)){
      clockwise1 = false;
      prev11 = false;    
    }
    // детектирование направления второго перехода (от 00)
    else if ((!Encoder_CLK)&&(Encoder_DT)&&(!prev11)){
      clockwise2 = false;
    }
    else if ((Encoder_CLK)&&(!Encoder_DT)&&(!prev11)){
      clockwise2 = true;   
    }
  }*/
}`

**Comment by GyverLibs** [comment]
Привет, это называется как закодил - так и работает. Дело не в совместимости библиотек, а во времени выполнения функций. Что то из этого полотна кода очень долго выполняется и из за этого идут пропуски опроса энкодера, как минимум библиотека Даллас вешает всё на секунду

**Comment by waw555** [comment]
Спасибо, большое за наводку. Пересмотрел видео уроки, заметил что в уроке про многозадачность используется термистор и это его опрос происходит с интервалом в 80 мс, а про Даллас другой урок, и там чётко сказано про 1 секунду. Спасибо ещё раз, буду пробовать.

**Comment by GyverLibs** [comment]
Другой урок - там и библиотека другая, которая асинхронно работает
