### ISSUE TITLE
Как я могу перевести этот диспетчер задач на микросекунды?

### ISSUE THREAD

**Issue by Denis20221** [GyverLibs/GyverOS#4]
Миллисекунды это хорошо, но есть ли возможность сменить временную единицу с миллисекунд на микросекунды?

**Comment by GyverLibs** [comment]
Добавил в версии 1.1:
объявить #define OS_MICROS перед подключением библиотеки в программе

**Comment by Denis20221** [comment]
Заработало с микросекундами. Огромное спасибо)
