### ISSUE TITLE
Вопрос на счет порядка выполнения задач

### ISSUE THREAD

**Issue by Denis20221** [GyverLibs/GyverOS#5]
Здравствуйте! Не могу понять, и в описании не нашел. Допустим при вызове OS.tick(); обнаруживается что есть 2 задачи которые нужно выполнить. Как библиотека их будет выполнять, сразу за один вызов OS.tick(), или сначала одну задачу при вызове тика, а при следующим вторую задачу ит.д.? Правильно ли я понял что GyverOS<5> OS ограничивает макс выполнение задач за один вызванный тик?

Иными словами, 2 большие функции к примеру разбить на кучу мелких, и чтоб они поочередно выполнялись. Раз вызвал тик, одна задача выполнилась, второй тик - следующая задача...

**Comment by GyverLibs** [comment]
Тик обрабатывает весь список задач за один вызов. При инициализации указывается максимальное количество задач, с которыми будет работать диспетчер, так как массив создаётся статически и его размер не меняется в процессе работы программы

**Comment by Denis20221** [comment]
Здравствуйте! Спасибо за ответ. Еще хотел спросить. OS.exec(0); вызывает функцию\задачу еще до такого как отработал последующий тик. Получается вызов идет в обход тика?

**Comment by GyverLibs** [comment]
Привет, exec() вызывает указанную задачу там, где будет вызвана эта функция, независимо от тика и состояния задачи
