### ISSUE TITLE
Какой максимальный период можно установить?

### ISSUE THREAD

**Issue by kmsmi** [GyverLibs/GyverOS#6]
Какой максимальный период можно установить?
Больше 10 секунд не работает а нужны минуты.
PS: Atmega328PB

**Comment by GyverLibs** [comment]
`uint32_t` - около 50 суток. Чую пригодится вот этот урок https://alexgyver.ru/lessons/compute/

**Comment by kmsmi** [comment]
Странно, у меня uint32_t определена в stdint.h как  unsigned  int  ` typedef unsigned int uint32_t` (Plftformio MiniCore)
Ладно, поразбираюсь.

**Comment by GyverLibs** [comment]
Как задаётся период? Случайно не `секунды*1000`?

**Comment by kmsmi** [comment]
Почти. ` (uint32_t)minute * 60000 `
Но разумеется пробовал и просто в миллисекундах указывать.

**Comment by GyverLibs** [comment]
Тогда странно, у меня работает

**Comment by kmsmi** [comment]
Что то я запарился. Только сейчас вспомнил что есть и другой таймер где отрабатывает минуту и больше без проблем.
Проблема только с этим таймером. Но тоже не понятно. Если бы не работал совсем это ладно, а то секунды считает а минуты уже нет.
Ладно, будем смотреть.

**Comment by GyverLibs** [comment]
Возможно не хватает `(uint32_t)` в 55 строке
`tmrs[i] += (uint32_t)prds[i] * (left / prds[i]);`

**Comment by kmsmi** [comment]
Тему можно закрывать. Тогда так и не разобрался, перешел на другую библиотеку, вернее на ту с которой перешел на GyverOS. Там как мне казалось все работало. Но в итоге как раз с этим же таймеров вылезла проблема. Короче нашел у себя косяк.
